name: "CodeQL Analysis"
env:
  TARGET_LANGUAGE: "javascript" # To change depending of your project
on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: ${{ env.TARGET_LANGUAGE }}
        build-mode: none
        packs: titouancharrier/cql-green-queries-${{ env.TARGET_LANGUAGE }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
      with:
        category: "green-it-java"
